### ISSUE TITLE
Image not displaying after converting from HTML

### ISSUE THREAD

**Issue by ThongDoo** [niuware/mui-rte#157]
I hardcoded a string that has html elements like this (only an img displayed as a figure)
![image](https://user-images.githubusercontent.com/20649539/85984471-6f240d00-ba13-11ea-9b22-0658c824b63b.png)

and displayed it in mui-rte using defaultValue={cState}, but it only showed up as an empty figure (an empty square/rectangle).
The figure, upon clicking, will display the Media component, with the registered width & height, but no url.

I checked the ContentState using convertToRaw for converting issues but it does contain the same contentBlocks & entityMap of the coded value, so that might not be an issue.

I can insert a picture & convert it to html with no problem.

**Comment by niuware** [comment]
The editor uses a custom block (`Media`) to render the image (`img`), the problem is the `src` property is not being found on your editor state.

**Comment by ThongDoo** [comment]
> the problem is the `src` property is not being found on your editor state.

Can you please explain this further?
Because I thought converting the html using the pictured methods would have included the ### src property.

**Comment by niuware** [comment]
I believe the problem is that the `src` property is not being saved in the `data` for the block (`Media`). Currently the editor saves this properties (`src`, `width`, etc.) on the `data` of the block.

**Comment by patrykkarny** [comment]
hey, @niuware, I'm having the same issue, I was trying to load the HTML with [this](https://github.com/sstur/draft-js-utils/tree/master/packages/draft-js-import-html) library as well as based on the [example](https://github.com/niuware/mui-rte/blob/master/examples/load-html/index.tsx) but it didn't work for both cases. Not sure how to map the `Media` block in order to add `src` property into the `data` object. Do you have some suggestions?

**Comment by thngdude** [comment]
@patrykkarny @ThongDoo I ran into this issue, too. You need to add a src key/value to the promise response for `insertAtomicBlockAsync`. The url value doesn't appear to translate into anything as html.
