### ISSUE TITLE
I want to add another button in the editor (NOT in the controls), how to provide state to that particular independent button.

### ISSUE THREAD

**Issue by Zabi-Progton** [niuware/mui-rte#50]
I understand that one way of doing so is to add a custom control and use the onClick on that control to get the state of the editor, is there another way to get the state of the editor, why can' t I get the state of the editor?? Please help out. Also please let me know how to make this editor a controlled input, I can give the value from the change and the onChange is hooked up to the state, whenever I try this, the editor starts typing in reverse and I am unable to fix that.

**Comment by niuware** [comment]
@Zabi-Progton Currently the state is controlled by the `MUIRichTextEditor` component, the reason is to avoid the need of the `draft-js` API directly. This package current API provides several ways to interact with the editor content, but now is not possible to modify the editor state directly. This may change in future versions.

Currently you can only alter the content state by modifying the `value` property which receives a stringified `RawDraftContentState` object. You can see the effect that sets this value here: https://github.com/niuware/mui-rte/blob/fe7c58704cbb899e4927ea6d2111726404bd5df9/src/MUIRichTextEditor.tsx#L185
