### ISSUE TITLE
'link' control not working as expected (mui-rte: v 1.11.0)

### ISSUE THREAD

**Issue by corneliushka** [niuware/mui-rte#72]
Hello, at first thank you for this MUI/Draft.js library.

At first I stumbled on a bug .. 
> I wonder how to use (or create) the link embedded control ? You provide it but I cannot figure how to use it. The button link doesn't do anything. 

... then I find out (maybe why).

You provide a basic example on Codesandbox which is on mui-rte 1.11.0. I think that the bug is related to this last version. cf. : https://codesandbox.io/s/mui-rte-basic-ypfdo?fontsize=14

We figure out that v. 1.9.3 works fine. The bug must lies somewhere in the toolbar (cf. release note 1.10), I think that maybe the popover position isn't correctly initialized.

Have a nice day.

**Comment by corneliushka** [comment]
You provide a basic example on Codesandbox which is on mui-rte 1.11.0. I think that the bug is related to this last version. 
We figure out that 1.9.3 works fine. The bug must lies somewhere in the toolbar, I think that maybe the popover position isn't correctly initialized.

**Comment by niuware** [comment]
Hi @corneliushka,
Thank you for the heads up, I will fix this soon.

**Comment by niuware** [comment]
@corneliushka Fixed on version `1.12.0` :)

**Comment by p08kast** [comment]
We are facing a similar issue. We use mui-rte v.2.0.1 with material 5.1. We render the rte within a modal that is inside an iframe. While everything else works as expected, clicking the linking button on the toolbar does absolutely nothing.

@corneliushka what was the initial reason you mention in your original post?

Btw, the sandbox provided is working just fine for me.

**Comment by corneliugaina** [comment]
@p08kast  My original post pointed a bug with the demo (and production code on some version) where the prompt of linking wasn't working. 

Speaking of your issue, I suspect that your modal "hides" the popup because of z-index of something like that. Beware that in MUI (4 or 5), the components have a standard zIndex that you can override of course in your custom theme. 

Try just to render you component outside of the modal/dialog/popup, just to be sure that it's about this. Otherwise I didn't yet use mui-rte with MUI5 but there's some issues and update about this. Didn't investigated 

[mui z-index docs](https://mui.com/customization/z-index/)

**Comment by p08kast** [comment]
I am aware of the z-index issues, however the popover doesn't seem to be appended in the DOM at all. I've also tried setting disablePortal to true in case it was being appended outside my iframe but to no avail.
