### ISSUE TITLE
Links are relative instead of absolute

### ISSUE THREAD

**Issue by thierryMic** [niuware/mui-rte#86]
Thank you for putting this put there it is really helpful.

I am not sure if this is happening only for me but links are relative.
In the example below, the link will open to: www.localhost:3000/www.github.com
I suspect it can be fixed by pre-pending the href with '//' in the Link component:

```
const Link: React.FC<ILinkProps> = (props: ILinkProps) => {
    const { url } = props.contentState.getEntity(props.entityKey).getData()
    return (
        <a
            href={`//${url}`}
```

![image](https://user-images.githubusercontent.com/21054294/76137878-01d02300-6096-11ea-8a57-ddcc94baa03b.png)

![image](https://user-images.githubusercontent.com/21054294/76137887-13b1c600-6096-11ea-965a-a309d1c9d92b.png)

**Comment by mmaass** [comment]
I get the same result. And that's perfectly fine by me. Just use https://www.github.com, if you want an absolute link. This address is the same you would get, if you copy an URL from your browser's address bar.

**Comment by thierryMic** [comment]
Hi @mmaass, as the programmer it is fine by me too. However the RTE will be used by a multitude of users and it would be better if they could enter a url and have it work as one would intuitively think it does without having to worry about the communication protocol.
Perhaps we could have some kind of prop which allows us to specify whether we want the links to behave as relative or absolute links?

**Comment by niuware** [comment]
@thierryMic Thanks for your comment. This is the intended behavior. Usually, a user just copy and paste the link instead of typing it and I believe additional configuration for a link is not necessary. You can always create your own [Atomic Custom Block](https://github.com/niuware/mui-rte/tree/master/examples/atomic-custom-block) if you require a link component with specific options.

Hope this helps you out.
